<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Manoj" failures="13" tests="30" name="EmployeeRestAPITest" time="28.176" errors="0" timestamp="2024-03-08T11:33:21 IST">
  <testcase classname="com.employeeapi.testcase.TC005_Delete_Employee_Record" name="@BeforeClass createEmployee" time="1.053">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at com.employeeapi.testcase.TC005_Delete_Employee_Record.createEmployee(TC005_Delete_Employee_Record.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 31 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass createEmployee -->
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkContentEncoding" time="0.018"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkContentLength" time="0.004"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkContentType" time="0.003"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkResponseTime" time="0.005"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkResposeBody" time="0.034"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkServerType" time="0.003"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkStatusCode" time="0.007"/>
  <testcase classname="com.employeeapi.testcase.TC001_Get_All_Employees" name="checkStatusLine" time="0.007"/>
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkContentEncoding" time="0.004"/>
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkContentType" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcase.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:111)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkResponseTime" time="0.002"/>
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkResposeBody" time="0.039">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcase.TC004_Put_Employee_Record.checkResposeBody(TC004_Put_Employee_Record.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkServerType" time="0.003"/>
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkStatusCode" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcase.TC004_Put_Employee_Record.checkStatusCode(TC004_Put_Employee_Record.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcase.TC004_Put_Employee_Record" name="checkStatusLine" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcase.TC004_Put_Employee_Record.checkStatusLine(TC004_Put_Employee_Record.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkContentLength" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [150] but found [595]">
      <![CDATA[java.lang.AssertionError: expected [150] but found [595]
at com.employeeapi.testcase.TC002_Get_Single_Employee_Record.checkContentLength(TC002_Get_Single_Employee_Record.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLength -->
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkContentType" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcase.TC002_Get_Single_Employee_Record.checkContentType(TC002_Get_Single_Employee_Record.java:89)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkResponseTime" time="0.003"/>
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkResposeBody" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcase.TC002_Get_Single_Employee_Record.checkResposeBody(TC002_Get_Single_Employee_Record.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkServerType" time="0.002"/>
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkStatusCode" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcase.TC002_Get_Single_Employee_Record.checkStatusCode(TC002_Get_Single_Employee_Record.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcase.TC002_Get_Single_Employee_Record" name="checkStatusLine" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcase.TC002_Get_Single_Employee_Record.checkStatusLine(TC002_Get_Single_Employee_Record.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcase.TC005_Delete_Employee_Record" name="checkResposeBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResposeBody -->
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkContentEncoding" time="0.003"/>
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkContentType" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcase.TC003_Post_Employee_Record.checkContentType(TC003_Post_Employee_Record.java:108)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkResponseTime" time="0.008"/>
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkResposeBody" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcase.TC003_Post_Employee_Record.checkResposeBody(TC003_Post_Employee_Record.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkResposeBody -->
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkServerType" time="0.004"/>
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkStatusCode" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcase.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcase.TC003_Post_Employee_Record" name="checkStatusLine" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcase.TC003_Post_Employee_Record.checkStatusLine(TC003_Post_Employee_Record.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
</testsuite> <!-- EmployeeRestAPITest -->
